import { Avatar } from '../types/avatar.types';

export const DEFAULT_AVATARS: Avatar[] = [
  // --- FEMALE AVATARS (20) ---
  {
    id: 'sophia-casual',
    name: 'Sophia',
    gender: 'female',
    category: 'casual',
    language: 'Russian (RU) & English (US)',
    energyLevel: 9,
    speakingStyle: 'Радостный, дружелюбный, разговорный ритм',
    thumbnail: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Обаятельный блогер в очках и джинсовой куртке. Идеально для лайфстайла и блогов.',
    avatarStyle: 'close-up',
    age: 24,
    clothingStyle: 'Casual / Джинсовый',
    roleType: 'Creator'
  },
  {
    id: 'elena-corporate',
    name: 'Elena',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU) & German (DE)',
    energyLevel: 7,
    speakingStyle: 'Профессиональный, спокойный, глубокий тон',
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Бизнес-леди в строгом пиджаке. Прекрасна для отчетов и корпоративных презентаций.',
    avatarStyle: 'normal',
    age: 35,
    clothingStyle: 'Business / Деловой костюм',
    roleType: 'Business'
  },
  {
    id: 'diana-creative',
    name: 'Diana',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU) & French (FR)',
    energyLevel: 10,
    speakingStyle: 'Экстравертный, энергичный, вдохновляющий',
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-excited-woman-talking-to-camera-41852-large.mp4',
    description: 'Инфлюенсер в дизайнерской одежде. Привлекает внимание с первых секунд, удерживая ритм.',
    avatarStyle: 'close-up',
    age: 28,
    clothingStyle: 'Creative / Яркий стиль',
    roleType: 'Podcast'
  },
  {
    id: 'anna-lifestyle',
    name: 'Анна',
    gender: 'female',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Искренний, теплый, мягкий',
    thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Контент-мейкер в стильном худи. Подходит для разбора трендов и молодежных новостей.',
    avatarStyle: 'close-up',
    age: 22,
    clothingStyle: 'Streetwear / Худи',
    roleType: 'Creator'
  },
  {
    id: 'victoria-coach',
    name: 'Виктория',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Уверенный, менторский, вовлекающий',
    thumbnail: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Сертифицированный коуч в блейзере. Идеальный спикер для курсов личной эффективности.',
    avatarStyle: 'normal',
    age: 41,
    clothingStyle: 'Smart Casual / Блейзер',
    roleType: 'Coach'
  },
  {
    id: 'natalia-teacher',
    name: 'Наталья',
    gender: 'female',
    category: 'educational',
    language: 'Russian (RU) & English (US)',
    energyLevel: 8,
    speakingStyle: 'Четкий, размеренный, академический',
    thumbnail: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Преподаватель в очках и рубашке. Идеальна для лекций, вебинаров и методических инструкций.',
    avatarStyle: 'normal',
    age: 32,
    clothingStyle: 'Classic / Рубашка с очками',
    roleType: 'Teacher'
  },
  {
    id: 'ekaterina-news',
    name: 'Екатерина',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Динамичный, журналистский, убедительный',
    thumbnail: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Ведущая новостей в лаконичном блузоне. Подходит для медиа, прессы и быстрых дайджестов.',
    avatarStyle: 'normal',
    age: 26,
    clothingStyle: 'Smart Business / Блуза',
    roleType: 'Creator'
  },
  {
    id: 'maria-consult',
    name: 'Мария',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 7,
    speakingStyle: 'Спокойный, экспертный, рассудительный',
    thumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Консультант в сдержанном костюме. Отличное решение для разбора юридических и налоговых вопросов.',
    avatarStyle: 'normal',
    age: 38,
    clothingStyle: 'Business / Темный жакет',
    roleType: 'Coach'
  },
  {
    id: 'julia-podcast',
    name: 'Юлия',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Бархатистый голос, радиоформат, живая улыбка',
    thumbnail: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-excited-woman-talking-to-camera-41852-large.mp4',
    description: 'Харизматичный подкастер в стильных наушниках. Создает уютную атмосферу диалога со зрителем.',
    avatarStyle: 'close-up',
    age: 29,
    clothingStyle: 'Creator Style / Свитер',
    roleType: 'Podcast'
  },
  {
    id: 'daria-academy',
    name: 'Дарья',
    gender: 'female',
    category: 'educational',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Информативный, структурированный, вдохновляющий',
    thumbnail: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Куратор онлайн-школы в минималистичном стиле. Подходит для пошаговых гайдов.',
    avatarStyle: 'close-up',
    age: 31,
    clothingStyle: 'Minimalist / Тонкая кофта',
    roleType: 'Teacher'
  },
  {
    id: 'olga-expert',
    name: 'Ольга',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Убедительный, весомый, статусный',
    thumbnail: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Старший аналитик в изысканном деловом образе. Предназначена для стратегических докладов.',
    avatarStyle: 'normal',
    age: 45,
    clothingStyle: 'Executive / Белая блуза',
    roleType: 'Business'
  },
  {
    id: 'irina-casual',
    name: 'Ирина',
    gender: 'female',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Мягкий, вовлекающий, легкий',
    thumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Дизайнер в легком кардигане. Для креативных портфолио, ревью дизайнов и влогов.',
    avatarStyle: 'close-up',
    age: 27,
    clothingStyle: 'Boho Casual / Кардиган',
    roleType: 'Creator'
  },
  {
    id: 'anastasia-host',
    name: 'Анастасия',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 10,
    speakingStyle: 'Быстрый темп, вовлекающие интонации, экспрессивный',
    thumbnail: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-excited-woman-talking-to-camera-41852-large.mp4',
    description: 'Медиа-шоу хост. Ведет развлекательные программы, конкурсы и яркие интервью.',
    avatarStyle: 'close-up',
    age: 25,
    clothingStyle: 'Modern Creator / Модный топ',
    roleType: 'Podcast'
  },
  {
    id: 'kristina-doc',
    name: 'Кристина',
    gender: 'female',
    category: 'educational',
    language: 'Russian (RU) & English (US)',
    energyLevel: 7,
    speakingStyle: 'Информативный, заботливый, размеренный',
    thumbnail: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Популяризатор науки, медицинский спикер. Отличное произношение терминов.',
    avatarStyle: 'normal',
    age: 33,
    clothingStyle: 'Medical / Белый медицинский воротник',
    roleType: 'Teacher'
  },
  {
    id: 'alina-tech-expert',
    name: 'Алина',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Четкий, напористый, экспертный',
    thumbnail: 'https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Финтех-блогер. Подробно рассказывает про криптовалюты, инвестиции и стартапы.',
    avatarStyle: 'close-up',
    age: 29,
    clothingStyle: 'High-Tech / Водолазка',
    roleType: 'Business'
  },
  {
    id: 'polina-lifestyle',
    name: 'Полина',
    gender: 'female',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Мечтательный, вовлекающий, дружелюбный',
    thumbnail: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-excited-woman-talking-to-camera-41852-large.mp4',
    description: 'Влогер о путешествиях и гастрономии. Живые интонации реального человека.',
    avatarStyle: 'close-up',
    age: 23,
    clothingStyle: 'Summer Casual / Футболка',
    roleType: 'Creator'
  },
  {
    id: 'margarita-psychology',
    name: 'Маргарита',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Эмпатичный, глубокий, терапевтический',
    thumbnail: 'https://images.unsplash.com/photo-1534751516642-a131ffd473fd?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Практикующий психотерапевт. Приятный убаюкивающий, но уверенный тембр.',
    avatarStyle: 'normal',
    age: 36,
    clothingStyle: 'Casual Tailored / Жакет пастельного тона',
    roleType: 'Coach'
  },
  {
    id: 'veronika-art',
    name: 'Вероника',
    gender: 'female',
    category: 'educational',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Интеллигентный, воодушевленный, культурный',
    thumbnail: 'https://images.unsplash.com/photo-1542103749-8ef59b94f4d3?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-glasses-talking-to-camera-41851-large.mp4',
    description: 'Искусствовед, лектор. Подходит для лекций о кино, живописи и архитектуре.',
    avatarStyle: 'close-up',
    age: 28,
    clothingStyle: 'Artistic / Очки и шарф',
    roleType: 'Teacher'
  },
  {
    id: 'svetlana-executive',
    name: 'Светлана',
    gender: 'female',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 7,
    speakingStyle: 'Строгий, авторитетный, структурированный',
    thumbnail: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-woman-working-at-office-and-talking-41850-large.mp4',
    description: 'Генеральный директор, бизнес-коуч. Фокус на результатах и лидерстве.',
    avatarStyle: 'normal',
    age: 43,
    clothingStyle: 'Business Formal / Строгий костюм с рубашкой',
    roleType: 'Coach'
  },
  {
    id: 'elizabeth-podcast-creative',
    name: 'Элизабет',
    gender: 'female',
    category: 'creative',
    language: 'Russian (RU) & English (UK)',
    energyLevel: 9,
    speakingStyle: 'Стильный харизматичный тембр, выразительная мимика',
    thumbnail: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-excited-woman-talking-to-camera-41852-large.mp4',
    description: 'Англоязычный продюсер курсов. Оптимально для дубляжа и мультиязычных подкастов.',
    avatarStyle: 'close-up',
    age: 30,
    clothingStyle: 'Urban Creative / Черная водолазка',
    roleType: 'Podcast'
  },

  // --- MALE AVATARS (20) ---
  {
    id: 'charles-business',
    name: 'Charles',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU) & English (US)',
    energyLevel: 8,
    speakingStyle: 'Уверенный, статусный, авторитетный оратор',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Ведущий в деловом костюме-тройка. Для финансовых презентаций.',
    avatarStyle: 'normal',
    age: 34,
    clothingStyle: 'Business / Деловой костюм-тройка',
    roleType: 'Business'
  },
  {
    id: 'marcus-tech',
    name: 'Marcus',
    gender: 'male',
    category: 'educational',
    language: 'Russian (RU) & English (US)',
    energyLevel: 8,
    speakingStyle: 'Аналитический, спокойный, методичный',
    thumbnail: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'ИТ-специалист в рубашке. Оптимизирован для технических обзоров и разбора кода.',
    avatarStyle: 'normal',
    age: 40,
    clothingStyle: 'Smart Casual / Рубашка',
    roleType: 'Teacher'
  },
  {
    id: 'alex-creative',
    name: 'Alex',
    gender: 'male',
    category: 'creative',
    language: 'Russian (RU) & Spanish (ES)',
    energyLevel: 9,
    speakingStyle: 'Современный, ритмичный, вовлекающий',
    thumbnail: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Стильный дизайнер, арт-директор. Отлично удерживает молодежную аудиторию.',
    avatarStyle: 'close-up',
    age: 29,
    clothingStyle: 'Creative / Кожаный пиджак',
    roleType: 'Creator'
  },
  {
    id: 'mikhail-expert',
    name: 'Михаил',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Глубокий харизматичный баритон, весомая подача',
    thumbnail: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Эксперт топ-менеджмента в брендовом пиджаке. Премии, отчеты, инсайды рынка.',
    avatarStyle: 'normal',
    age: 45,
    clothingStyle: 'Executive / Бизнес костюм',
    roleType: 'Business'
  },
  {
    id: 'alexander-street',
    name: 'Александр',
    gender: 'male',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Энергичный, быстрый темп, разговорный сленг',
    thumbnail: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Популярный рэп-исполнитель/блогер. Бомбический выбор для прогревов соцсетей.',
    avatarStyle: 'close-up',
    age: 26,
    clothingStyle: 'Streetwear / Оверсайз футболка',
    roleType: 'Creator'
  },
  {
    id: 'dmitry-prof',
    name: 'Дмитрий',
    gender: 'male',
    category: 'educational',
    language: 'Russian (RU)',
    energyLevel: 7,
    speakingStyle: 'Доброжелательный, аргументированный, понятный',
    thumbnail: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Доцент, ИТ-координатор в пиджаке поверх поло. Идеальный лектор и наставник.',
    avatarStyle: 'normal',
    age: 35,
    clothingStyle: 'Smart Casual / Пиджак и поло',
    roleType: 'Teacher'
  },
  {
    id: 'andrey-podcast',
    name: 'Андрей',
    gender: 'male',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Интонации интервьюера, паузы для раздумий',
    thumbnail: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Ведущий авторского подкаста. Создает эффект искреннего, глубокого разговора.',
    avatarStyle: 'close-up',
    age: 28,
    clothingStyle: 'Podcast Style / Рубашка поверх футболки',
    roleType: 'Podcast'
  },
  {
    id: 'maxim-sales',
    name: 'Максим',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 10,
    speakingStyle: 'Напористый, мотивирующий, продающий ритм',
    thumbnail: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Бизнес-тренер по продажам. Заряжает энергией действовать прямо сейчас.',
    avatarStyle: 'normal',
    age: 32,
    clothingStyle: 'Smart Business / Синяя рубашка',
    roleType: 'Coach'
  },
  {
    id: 'sergey-sport',
    name: 'Сергей',
    gender: 'male',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Прямолинейный, дисциплинирующий, бодрый',
    thumbnail: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Фитнес-инструктор, коуч по здоровому образу жизни. Лаконичный разговорный слог.',
    avatarStyle: 'close-up',
    age: 39,
    clothingStyle: 'Sportswear / Бомбер',
    roleType: 'Coach'
  },
  {
    id: 'pavel-lecture',
    name: 'Павел',
    gender: 'male',
    category: 'educational',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Убедительный, научно-технический, уравновешенный',
    thumbnail: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Популяризатор физики и инженерии в вельветовом пиджаке. Повышенный уровень удержания.',
    avatarStyle: 'normal',
    age: 42,
    clothingStyle: 'Professor / Вельветовый пиджак',
    roleType: 'Teacher'
  },
  {
    id: 'roman-opinion',
    name: 'Роман',
    gender: 'male',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Пытливый, провокационный, медийный',
    thumbnail: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Ютуб-исследователь заговоров и трендов на технологиях. Хитрый взгляд.',
    avatarStyle: 'close-up',
    age: 31,
    clothingStyle: 'Creator / Черный ворот',
    roleType: 'Podcast'
  },
  {
    id: 'ivan-lawyer',
    name: 'Иван',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 7,
    speakingStyle: 'Красивый дикторский слог, академические паузы',
    thumbnail: 'https://images.unsplash.com/photo-1534030219386-817edd32d917?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Адвокат, юрист в сером костюме в полоску. Имидж стабильности и успеха для клиентов.',
    avatarStyle: 'normal',
    age: 37,
    clothingStyle: 'High Corporate / Костюм в полоску',
    roleType: 'Business'
  },
  {
    id: 'denis-young',
    name: 'Денис',
    gender: 'male',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 10,
    speakingStyle: 'Сверхмолодой, амбициозный, быстрый тембр',
    thumbnail: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Молодой основатель стартапа в яркой кофте. О птичках, инвестициях и ИИ джемах.',
    avatarStyle: 'close-up',
    age: 24,
    clothingStyle: 'Tech-Pop / Ярко-желтая кофта',
    roleType: 'Creator'
  },
  {
    id: 'arthur-tutor',
    name: 'Артур',
    gender: 'male',
    category: 'educational',
    language: 'Russian (RU) & English (UK)',
    energyLevel: 8,
    speakingStyle: 'Интеллигентный, воодушевляющий, глубокий',
    thumbnail: 'https://images.unsplash.com/photo-1506803682981-6e718a9dd3ee?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Лингвист, коуч по английскому языку. Великолепный аудиоакцент.',
    avatarStyle: 'normal',
    age: 28,
    clothingStyle: 'Oxford Casual / Твидовый пиджак',
    roleType: 'Teacher'
  },
  {
    id: 'konstantin-hr',
    name: 'Константин',
    gender: 'male',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Располагающий, внимательный, эмпатичный',
    thumbnail: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Ведущий HR-специалист, спикер конференций о найме. Позитивная манера общения.',
    avatarStyle: 'normal',
    age: 36,
    clothingStyle: 'Business Casual / Джемпер',
    roleType: 'Coach'
  },
  {
    id: 'vladislav-ceo',
    name: 'Владислав',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Лаконичный, прагматичный, лидерский',
    thumbnail: 'https://images.unsplash.com/photo-1504257404762-5551ad27264b?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Основатель миллиардного ИТ-холдинга. Высокий класс ведения переговоров.',
    avatarStyle: 'normal',
    age: 30,
    clothingStyle: 'Smart Executive / Дорогой пиджак без галстука',
    roleType: 'Business'
  },
  {
    id: 'danila-crypto',
    name: 'Данила',
    gender: 'male',
    category: 'casual',
    language: 'Russian (RU)',
    energyLevel: 10,
    speakingStyle: 'Динамичный, яркий, крипто-сленговый',
    thumbnail: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Крипто-трейдер в очках. Быстрые инсайты, разборы графиков и сигналов рынка.',
    avatarStyle: 'close-up',
    age: 22,
    clothingStyle: 'Tech Web3 / Очки и худи с мерчем',
    roleType: 'Creator'
  },
  {
    id: 'ilya-media',
    name: 'Илья',
    gender: 'male',
    category: 'creative',
    language: 'Russian (RU)',
    energyLevel: 8,
    speakingStyle: 'Голос рассказчика, атмосферный сторителлинг',
    thumbnail: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-creative-man-talking-to-camera-41853-large.mp4',
    description: 'Медиадиректор, хост исторических и научных циклов. Увлекает с первой фразы.',
    avatarStyle: 'close-up',
    age: 33,
    clothingStyle: 'Podcast Style / Трендовая рубашка',
    roleType: 'Podcast'
  },
  {
    id: 'nikita-data',
    name: 'Никита',
    gender: 'male',
    category: 'educational',
    language: 'Russian (RU) & English (US)',
    energyLevel: 8,
    speakingStyle: 'Разумный, фактологический, экспертный',
    thumbnail: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-man-holding-a-smartphone-and-talking-41857-large.mp4',
    description: 'Специалист по Data Science и ИИ. Пошагово объясняет интеграцию сложных ML систем.',
    avatarStyle: 'normal',
    age: 27,
    clothingStyle: 'Geek / Черная футболка с принтом',
    roleType: 'Teacher'
  },
  {
    id: 'artem-speaker',
    name: 'Артем',
    gender: 'male',
    category: 'business',
    language: 'Russian (RU)',
    energyLevel: 9,
    speakingStyle: 'Харизматичный спикер TED-формата',
    thumbnail: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&q=80&w=300&h=300',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-businessman-talking-to-camera-at-office-41849-large.mp4',
    description: 'Спикер международных конференций. Захватывает внимание, жесты руками.',
    avatarStyle: 'normal',
    age: 33,
    clothingStyle: 'TED Style / Синий пиджак и белая футболка',
    roleType: 'Coach'
  }
];

export const CATEGORY_LABELS: Record<string, string> = {
  business: 'Бизнес / Костюм',
  casual: 'Повседневный',
  educational: 'Образование',
  creative: 'Креативный'
};

export const GENDER_LABELS: Record<string, string> = {
  male: 'Мужской',
  female: 'Женский'
};

// Russian Voices definition (Requirement 3: "Русские голоса")
export interface RussianVoice {
  id: string; // voice_id inside ElevenLabs
  name: string;
  gender: 'male' | 'female';
  speakingStyle: string;
  emotionalProfile: string;
  previewText: string;
}

export const RUSSIAN_VOICES: RussianVoice[] = [
  {
    id: 'pqH6THCHvgSzSg3749S8', // Alexei ElevenLabs multilingual RU male
    name: 'Алексей',
    gender: 'male',
    speakingStyle: 'Уверенный бизнес-спикер, YouTube-ведущий',
    emotionalProfile: 'Интеллектуальный, авторитетный и весомый тембр',
    previewText: 'Здравствуйте! Это тест премиального русского AI-голоса Алексей. Мой темп идеально оптимизирован для бизнес-презентаций и обучающих вебинаров.'
  },
  {
    id: 'IKne3meq5aC27shg036e', // Dmitry ElevenLabs multilingual RU male
    name: 'Дмитрий',
    gender: 'male',
    speakingStyle: 'Глубокий харизматичный подкастер, интервьюер',
    emotionalProfile: 'Бархатистый баритон с теплыми разговорными интонациями',
    previewText: 'Привет! На связи Дмитрий. Наш голос звучит искренне и кинематографично — так, словно мы записываем эпизод прямо в профессиональной студии.'
  },
  {
    id: 'g5CIjv2V06O0Bdf0xW6K', // Maxim ElevenLabs multilingual RU male
    name: 'Максим',
    gender: 'male',
    speakingStyle: 'Динамичный ИТ-блогер, энергичный лектор',
    emotionalProfile: 'Бодрый, молодежный и технологичный эмоциональный профиль',
    previewText: 'Приветствуем! Это тест голоса Максим. Яркие интонации, быстрый темп и вовлечение с первых секунд — идеальное решение для шортсов и влогов.'
  },
  {
    id: 'EXAVITQu4vr4xnSDXMaL', // Anna ElevenLabs multilingual RU female
    name: 'Анна',
    gender: 'female',
    speakingStyle: 'Теплый бьюти-влогер, заботливый медитативный гид',
    emotionalProfile: 'Эмпатичный, мягкий и светлый женский голос',
    previewText: 'Рада познакомиться! С вами Анна. Этот голос создан для уютного общения, лайфстайл-роликов и разбора терапевтических тем.'
  },
  {
    id: 'ErXwobaYiN019PkySvjV', // Viktoria ElevenLabs multilingual RU female
    name: 'Виктория',
    gender: 'female',
    speakingStyle: 'Бизнес-консультант, статусная ведущая новостей',
    emotionalProfile: 'Артикулированная, спокойная и уверенная профессиональная манера',
    previewText: 'Здравствуйте! Я Виктория. Мой голос сочетает холодный аналитический склад и безупречную дикцию. Отличный выбор для корпоративного дайджеста.'
  },
  {
    id: 'LcfcDJNPlY75OxArInZp', // Ekaterina ElevenLabs multilingual RU female
    name: 'Екатерина',
    gender: 'female',
    speakingStyle: 'Учитель онлайн-академии, методист курсов',
    emotionalProfile: 'Понятный, вдохновляющий и дружелюбный академический профиль',
    previewText: 'Добрый день! Я Екатерина. Разложим сложную теорию по полочкам! Текстовые паузы и живое дыхание звучат абсолютно естественно для обучения.'
  }
];
